# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
