# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbloginfo',
            name='current_blog',
        ),
        migrations.RemoveField(
            model_name='userbloginfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='UserBlogInfo',
        ),
    ]
